---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: my-webapp
  labels:
    app: my-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      namespace: default
      labels:
        app: my-webapp
    spec:
      containers:
        - name: my-webapp
          image: gcr.io/spike-concourse/my-webapp
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: my-webapp-svc
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
  selector:
    app: my-webapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: my-webapp
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: my-webapp-svc
              servicePort: 8000
