apiVersion: v1
kind: Namespace
metadata:
  name: ___NAMESPACE___
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ___NAMESPACE___
  name: my-webapp
  labels:
    app: my-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      namespace: ___NAMESPACE___
      labels:
        app: my-webapp
    spec:
      containers:
        - name: my-webapp
          image: gcr.io/spike-concourse/my-webapp:dev-1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: ___NAMESPACE___
  name: my-webapp
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
  selector:
    app: my-webapp
