resources:
- name: github-spike-concourse
  type: git
  source:
    uri: https://github.com/BernardNotarianni/spike-concourse.git
- name: gcr.io/spike-concourse/my-webapp
  type: docker-image
  source:
    repository: gcr.io/spike-concourse/my-webapp
    username: _json_key
    password: {{gcr-key}}
jobs:
- name: tests
  plan:
  - get: github-spike-concourse
  - task: run-pytest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: grihabor/pytest
      run:
        path: sh
        args:
          - -exc
          - |
            pytest
      inputs:
      - name: github-spike-concourse
  - put: gcr.io/spike-concourse/my-webapp
    params: {build: github-spike-concourse/my-webapp}
